name = "Gato's Cobblemon Create"
author = "gatolocoses"
version = "1.0.44"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8952b588dc5de05661220ba0b386e7dae04216aed2723b25342d26ce4f754da1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
