name = "Gato's Cobblemon Create"
author = "gatolocoses"
version = "1.0.42"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "698d427e1716c8e7c531845b7660f335082f8af9176070bacf0bb45828079ce0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
