name = "Gato's Cobblemon Create"
author = "gatolocoses"
version = "1.0.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bed40fcab4fd36f18f169c17314dffd26b03092af8fabae035c6a3e6b894c73"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
